// Practical buyer guides share the live package data used by the pricing page.
export default function addGuides({add,pageHero,heading,link,faq,cta,plans,money,priceNote}) {
 const starter=plans.find(plan=>plan.name==='Starter');
 const business=plans.find(plan=>plan.name==='Business');
 const growth=plans.find(plan=>plan.name==='Growth');
 const monthlyCare=49;
 const guideParents=[{file:'guides.html',name:'Website guides'}];
 const priceFor=plan=>`${plan.name==='Growth'?'from ':''}${money(plan.build)}`;

 add('guides.html','Small Business Website Guides | Clearly Online','Practical guides to website costs and writing a useful brief. Plan your small business website, compare the scope and prepare for a clear quote.',`
${pageHero('Website guides','Plan your small<br><span>business website.</span>','Useful starting points for trades, service businesses and small teams planning a new website or a redesign. Work through the decisions before you choose a package.')}
<section class="section container">${heading('MAKE A MORE INFORMED START','Two guides.<br><span>Clearer decisions.</span>')}
<div class="two-columns"><article class="plain-block"><p class="eyebrow">UNDERSTAND THE COST</p><h3>What will your website cost?</h3><p>See how Clearly Online’s build prices work, what optional hosting adds over one or two years and which costs need a separate quote. Use the buyer’s checklist to compare the whole scope.</p>${link('website-cost-guide.html','Read the website cost guide')}</article><article class="plain-block"><p class="eyebrow">PREPARE YOUR BRIEF</p><h3>What should you tell your designer?</h3><p>Gather the details that shape a useful website: your customers, services, coverage, content and enquiry process. A short sample brief shows how to turn the prompts into a starting point.</p>${link('website-brief-checklist.html','Use the website brief checklist')}</article></div></section>
<section class="tinted section"><div class="container split"><div>${heading('CONNECT THE PLAN TO YOUR BUSINESS','Start with the work<br><span>you actually do.</span>')}</div><div><p>A tradesperson may need a useful quote request. An appointment business may need a clear route to its booking tool. A consultant may need more space to explain a service.</p><p>Explore <a href="websites-for-trades.html">websites for trades</a>, <a href="websites-for-appointments.html">appointment business websites</a> or <a href="websites-for-professionals.html">websites for professional services</a> for questions relevant to your work.</p><p>Ready to compare the options? The <a href="pricing.html">website pricing page</a> lists current package inclusions, while the <a href="web-design.html">website design page</a> explains the process.</p></div></div></section>${cta()}`,{pageType:'CollectionPage'});

 add('website-cost-guide.html','Website Cost Guide: Builds from '+money(starter.build)+' | Clearly Online','Understand Clearly Online website costs: '+money(starter.build)+', '+money(business.build)+' and from '+money(growth.build)+' builds, optional '+money(monthlyCare)+'/month hosting and care, plus costs to confirm in your quote.',`
${pageHero('Website cost guide','What does a small<br><span>business website cost?</span>','A guide to Clearly Online’s website packages, optional ongoing care and the details that change a quote. These are this studio’s guide prices, not a survey of the wider market.',guideParents)}
<section class="section container prose">
<nav class="section-nav" aria-label="On this website cost guide"><a href="guides.html">All website guides</a><a href="#build-cost">Build costs</a><a href="#ongoing-costs">Ongoing costs</a><a href="#quote-checklist">Quote checklist</a></nav>
<h2 id="build-cost">Start with the job your website needs to do</h2>
<p>A website budget makes more sense when it starts with the pages and actions you need. A small brochure site explaining one service has a different scope from a site with several service pages, booking requirements and a large amount of content to organise.</p>
<p>Clearly Online’s ${starter.name} package is ${money(starter.build)} for ${starter.pages.toLowerCase()}. ${business.name} is ${money(business.build)} for ${business.pages.toLowerCase()}. ${growth.name} starts at ${money(growth.build)}, with the page count and requirements agreed in the quote. These are one-off build prices; hosting is optional and separate.</p>
<p>Every package covers an agreed page list, design and development, responsive layouts, two consolidated design revision rounds, basic search setup, an agreed enquiry route, launch checks and a handover guide. Read the <a href="pricing.html#packages">full website package comparison</a> before choosing.</p>
<h2>Compare content and features separately</h2>
<p>More pages are only one reason a quote can change. Preparing photographs, writing service descriptions and importing existing material take work. Page planning and editing guidance are included; substantial copywriting, photography and brand identity need a separate scope.</p>
<p>Features need their own discussion. A link to an existing booking calendar is different from building a booking system. ${business.name} includes one agreed booking tool or advanced enquiry flow. Paid subscriptions, ecommerce, customer accounts and custom software are outside the standard brochure-site packages unless specifically quoted.</p>
<p>For example, a trades business might need separate pages for its main services and a quote form asking for a postcode and job description. An appointment business might need clear service choices and a link to its current diary. Choose the structure that answers customers’ questions rather than adding pages for their own sake.</p>
<h2 id="ongoing-costs">Allow for hosting and routine care</h2>
<p>Optional hosting and routine website care cost ${money(monthlyCare)} per month after launch. That adds ${money(monthlyCare*12)} over 12 months or ${money(monthlyCare*24)} over 24 months. You can instead choose compatible hosting elsewhere, with its own charges and support arrangements.</p>
<div class="table-scroll" role="region" aria-label="Clearly Online build and optional care cost comparison" tabindex="0"><table><caption>Build cost plus optional hosting and care</caption><thead><tr><th scope="col">Package</th><th scope="col">Build only</th><th scope="col">Build + 12 months care</th><th scope="col">Build + 24 months care</th></tr></thead><tbody>${plans.map(plan=>`<tr><th scope="row">${plan.name}</th><td>${priceFor(plan)}</td><td>${plan.name==='Growth'?'from ':''}${money(plan.build+monthlyCare*12)}</td><td>${plan.name==='Growth'?'from ':''}${money(plan.build+monthlyCare*24)}</td></tr>`).join('')}</tbody></table></div>
<p class="small">The totals assume care continues at the current guide rate. They are budgeting examples, not a price lock or a required 12- or 24-month commitment. Your agreement confirms the term, renewal pricing and notice.</p>
${priceNote}
<p>The care plan covers the agreed hosting, HTTPS setup, monitoring, scheduled backups and routine technical maintenance. Content changes, extra pages and new features are separate unless a defined allowance is agreed. Check the <a href="website-care.html">website care inclusions</a> for the boundaries and questions to ask.</p>
<h2>Budget for the costs outside the build</h2>
<p>Domain registration and renewal, business email, paid booking tools, premium licences and other third-party charges are separate unless your proposal includes them. Keep a list of who owns each account, when it renews and who pays the provider. A domain renewal and a website hosting fee pay for different things.</p>
<p>Basic search setup is included in the build. Ongoing <a href="local-seo.html">local SEO support</a> is a separate service with agreed priorities and fees. A website package does not include a promised search position or enquiry volume.</p>
<h2 id="quote-checklist">A checklist for comparing written quotes</h2>
<ol class="contact-steps"><li><strong>Pages:</strong> Which pages are included, and who provides their words and images?</li><li><strong>Features:</strong> Which forms and integrations will be delivered and tested?</li><li><strong>Review:</strong> How many design rounds are included, and what counts as a change of scope?</li><li><strong>Total:</strong> What is the build price, any applicable VAT, external cost and recurring fee?</li><li><strong>Payment:</strong> When are payments due, and what must be ready before work starts?</li><li><strong>Handover:</strong> Which files, accounts and editing instructions do you receive?</li><li><strong>Support:</strong> What happens after launch, and what are the notice and migration arrangements?</li></ol>
<p>Clearly Online’s proposed build payment schedule is 50% to book the project and 50% after approval, before launch and handover. The written proposal confirms the actual milestones, responsibilities and final total before you commit.</p>
<p>Use the <a href="website-brief-checklist.html">website brief checklist</a> to gather your requirements, then <a href="contact.html">share your project for a written quote</a>. An existing website address and a short list of priorities are a useful start.</p>
</section>${cta()}`,{parents:guideParents});

 add('website-brief-checklist.html','Small Business Website Brief Checklist | Clearly Online','Prepare a useful website brief with a practical checklist for services, customers, content, budget and enquiries, plus a clearly labelled example to adapt.',`
${pageHero('Website brief checklist','Write a useful<br><span>website brief.</span>','You do not need a technical specification to start. Use these prompts to explain your business, choose the right priorities and prepare for a more useful website quote.',guideParents)}
<section class="section container prose">
<nav class="section-nav" aria-label="On this website brief checklist"><a href="guides.html">All website guides</a><a href="#brief-prompts">Brief checklist</a><a href="#sample-brief">Example brief</a><a href="#next-step">Next step</a></nav>
<p>Short notes are fine. If you do not know an answer, mark it for discussion. For a redesign, include the existing website address and say what already works.</p>
<h2 id="brief-prompts">1. Describe your customers and the next step</h2>
<p>Who needs your service, and what are they trying to do when they visit? Choose the main action you want the website to support: request a quote, book an appointment or ask about a service. Explain what information makes a first enquiry useful to you.</p>
<p>Write down one practical problem to solve. “People cannot tell which areas we cover” gives more direction than “make it modern”. A clearer enquiry journey is a useful design goal.</p>
<h2>2. List services and genuine coverage</h2>
<p>List your main services in the language customers use. For each, note who it is for, common questions, any exclusions and whether it deserves a separate page. Add the towns or areas you actually serve and whether customers visit you or you travel to them.</p>
<p>For <a href="websites-for-trades.html">trades and home services</a>, useful details include job types, coverage boundaries and the information needed for a quote. Do not copy a long list of places into the brief just because you would like to appear in searches there.</p>
<h2>3. Map the contact or booking journey</h2>
<p>Explain what happens after a customer contacts you. Do you call back, request photographs, arrange a visit or direct them to a booking tool? Name any existing provider and the features you already use. A link, an embedded calendar and a custom system have different requirements.</p>
<p>An <a href="websites-for-appointments.html">appointment business website</a> may need service duration and preparation details near its booking link. A <a href="websites-for-professionals.html">professional services website</a> may need a short explanation of the introductory conversation. Only request information you need at that stage.</p>
<h2>4. Gather accurate content and real evidence</h2>
<p>Collect your logo, brand colours, service descriptions, current prices where appropriate, approved photographs and contact details. Note which materials are ready, need editing or still need creating. Include genuine qualifications, permissioned work examples or approved reviews where available.</p>
<p>Use your own business details and confirm permission for people, properties and work shown in photographs. You supply and approve specialist claims and policies. Substantial copywriting and original photography are separate from standard page planning and editing guidance.</p>
<h2>5. Explain what the existing website must keep</h2>
<p>If you are redesigning, list pages customers use, important downloads, forms, domain names and services connected to the site. Share available search information when appropriate so useful pages can be considered before changing the structure.</p>
<p>Record who controls the domain, hosting and business email. Do not put passwords in an enquiry. Account access and any redirect or migration requirements can be arranged during the project; the <a href="web-design.html">website design process</a> starts with reviewing the scope.</p>
<h2>6. Set a budget and a realistic priority order</h2>
<p>State your budget range, preferred launch date and why that date matters. Separate essentials from features that could wait. Name the person who approves the design and estimate when content and feedback will be ready.</p>
<p>Clearly Online’s guide builds are ${money(starter.build)}, ${money(business.build)} and from ${money(growth.build)}, with optional hosting and routine care at ${money(monthlyCare)} a month. Read the <a href="website-cost-guide.html">website cost guide</a> and <a href="pricing.html">package inclusions</a> before choosing. Third-party charges, content work and features can affect the final quote.</p>
<h2>7. Decide how you want to look after the site</h2>
<p>Who will change prices, add photographs or update service details after launch? List the edits you expect and how often. An agreed editing system and someone else making changes for you are different arrangements.</p>
<p>Say whether you want your own compatible host or <a href="website-care.html">Clearly Online hosting and care</a>. Ask for the support hours, backup arrangements, ongoing costs and handover responsibilities in the written proposal.</p>
<h2 id="sample-brief">An example brief to adapt</h2>
<p class="small">Illustrative example only. This describes an imagined project, not a Clearly Online client or completed website.</p>
<div class="plain-block"><p>“We run a small gardening business covering Sevenoaks and nearby areas. We want customers to understand our regular maintenance and one-off tidy-up services, check our coverage and request a quote with their postcode and a short job description.</p><p>We have a logo, service notes and our own photographs. We need help organising the pages. Our current website address will be included separately. The main priority is a clear mobile enquiry route; online payments are not needed.</p><p>Our budget is around ${money(business.build)} for the build, subject to the agreed scope. Please explain any extra costs and optional care. We would like to discuss a realistic launch date once you have reviewed the content. One person will collect and approve our feedback.”</p></div>
<h2 id="next-step">Send the useful starting points</h2>
<p>You can begin with your services, area, existing website, budget and main problem to solve. <a href="contact.html">Prepare an email enquiry</a>, then review and send it from your email app. The next step is a conversation and written scope, so unclear details can be worked through before work begins.</p>
</section>${cta()}`,{parents:guideParents});
}
