const menu=document.querySelector('.menu');
const nav=document.querySelector('#navigation');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&nav.classList.contains('open')){menu.setAttribute('aria-expanded','false');nav.classList.remove('open');menu.focus()}});
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{const mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));document.querySelectorAll('.amount').forEach(item=>item.querySelector('span').textContent=item.dataset[mode]);document.querySelectorAll('.amount small,.plan-term').forEach(item=>item.textContent=item.dataset[mode])}));
document.querySelectorAll('[data-plan]').forEach(link=>link.addEventListener('click',()=>{document.querySelector('[name=plan]').value=link.dataset.plan}));
document.querySelector('#brief-form').addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(event.currentTarget);const brief=`Website enquiry for Good Measure Studio\n\nName: ${data.get('name')}\nBusiness: ${data.get('business')||'Not supplied'}\nInterested in: ${data.get('plan')}\n\n${data.get('message')}`;const output=document.querySelector('#brief-output');output.value=brief;output.hidden=false;const status=document.querySelector('#form-status');try{await navigator.clipboard.writeText(brief);status.textContent='Your brief is copied. You can also select it below. Nothing has been sent.'}catch{status.textContent='Your brief is ready below. Select and copy it to save for later. Nothing has been sent.'}output.focus();output.select()});
document.querySelector('#year').textContent=new Date().getFullYear();
